# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf80b460348a174c271ff1b179d195dfaa9f41421393118c8e53e9f647c994ba3dbe8db70a33315f00c6d43b772035fc76ff3b15fe47f50d72908a407808ba69

test:
  secret_key_base: fe7ebb7ed308a596b60d2d2bb574fa247251fbc3c348148854b7d6c5bf28846327f7e2e37da63e582a267c37a6817f04084ccb4a7fca248f53c078c2d153c0de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
